create_task_treeの返答形式を変更する
gilmiwired/randuraft pull request #116
Opened 2024-06-04 13:59 UTC by KTR200

### 説明

- create_task_tree()の戻り値を、GeminiAPIのレスポンスDict[str, any]から、List[Task]に変更。
- create_task_tree()で使う変換関数dicts_to_tasks() を追加
- 上記変更に伴い、if __name__ == "__main__"内の、API結果をjsonに保存するコードを調整。

### 関連するIssue

### 動作再現方法・スクリーンショット

`cd randuraft_endpoint`して、`poetry run python3 -m services.create_task --input "同人ゲーム制作"`  を実行。

### チェックリスト

## その他

2024-06-04 14:36 UTC, gilmiwired reviewed
実際の実行結果のスクショとか貼ってくれると嬉しいっす！

2024-06-04 14:45 UTC, KTR200 commented
save_parts_to_json() を使用しなくなったが削除すべきかどうか。

2024-06-04 14:58 UTC, gilmiwired requested changes

2024-06-04 14:58 UTC, gilmiwired commented on randuraft_endpoint/services/create_task.py
> +    response = requests.post(url, headers=headers, json=data)  # TODO 戻す
不要コメント削除

2024-06-04 14:58 UTC, gilmiwired commented on randuraft_endpoint/services/create_task.py
> +def create_task_tree(task: str) -> List[Task] | Dict[str, str]:
これ元のコードがDict[str, str]で作ってしまっていた+エラー周りの情報もreturnさせてた名残でList[Task] | Dict[str, str]としてしまったと思うんだけどList[Task] | Dict[str, str]みたいに型ヒント曖昧になるのはあまりよろしくないのでList[Task]
にしてしまおう！

if以下のブロックtry-exceptでかこってエラー伝搬させるなり
elseの時にれレスポンス返さず伝搬
みたいな感じでやっちゃってください！

2024-06-04 14:58 UTC, gilmiwired commented on randuraft_endpoint/services/create_task.py
> +def create_task_tree(task: str) -> List[Task] | Dict[str, str]:
```suggestion
def create_task_tree(task: str) -> List[Task]:
```

2024-06-04 14:58 UTC, gilmiwired commented on randuraft_endpoint/services/create_task.py
> +
good
とりあえず保持で！

2024-06-04 15:01 UTC, gilmiwired commented
あ、save_parts_to_json() かこちらは削除でお願いします！

2024-06-04 15:19 UTC, KTR200 commented on randuraft_endpoint/services/create_task.py
> +    response = requests.post(url, headers=headers, json=data)  # TODO 戻す
修正。

2024-06-04 15:20 UTC, KTR200 commented
save_parts_to_json()  削除しました

2024-06-04 15:32 UTC, KTR200 commented on randuraft_endpoint/services/create_task.py
> +def create_task_tree(task: str) -> List[Task] | Dict[str, str]:
```
if response.status_code == 200:
    ...
else:
    message = f"Failed to retrieve data: {response.status_code}, {response.text}"
    raise ExternalAPIError(message)
```
みたいな感じですか？

2024-06-04 16:38 UTC, gilmiwired commented on randuraft_endpoint/services/create_task.py
> +def create_task_tree(task: str) -> List[Task] | Dict[str, str]:
です！
あと好みですが再利用するとかでなければ
```
ExternalAPIError(f"Failed to retrieve data: {response.status_code}, {response.text}")
```
みたいな感じでも！

2024-06-05 14:09 UTC, KTR200 commented on randuraft_endpoint/services/create_task.py
> +def create_task_tree(task: str) -> List[Task] | Dict[str, str]:
実装しました

2024-06-05 15:29 UTC, gilmiwired reviewed
review ready?

2024-06-08 14:39 UTC, gilmiwired requested changes

2024-06-08 14:39 UTC, gilmiwired commented on randuraft_endpoint/services/create_task.py
> +class ExternalApiError(Exception):
独自エラーいいね
エラークラスつくるならもう少し情報わたすなりカスタムメッセージ返すようにしてもいいかも

2024-06-08 14:39 UTC, gilmiwired commented on randuraft_endpoint/services/create_task.py
> +
ここの処理そんなに量ないんでcreate_task_treeに含めちゃっていいのかと！

2024-06-10 05:15 UTC, KTR200 commented on randuraft_endpoint/services/create_task.py
> +
確かに冗長なので、吸収させました。

2024-06-10 05:21 UTC, gilmiwired approved these changes
LGTM!

2024-06-10 15:42 UTC, merged

2024-06-15 15:00 UTC, gilmiwired reviewed
go